functions:
  - name: safe_divide
    description: Safely divide a numerator by a denominator where that value might be 0.
    config:
      schema:  # Ensure this matches the casing in your screenshot
      database: ANALYTICS
      volatility: deterministic
    arguments:
      - name: numerator
        data_type: number
      - name: denominator
        data_type: number
    returns:
      data_type: number

  - name: number_signal
    description: Check if it is a positive number
    config:
      schema: 
      database: ANALYTICS
      volatility: deterministic
    arguments:
      - name: numerator
        data_type: number
    returns:
      data_type: string

  - name: create_email
    description: Generates a company email with a customer name and id
    config:
      schema: 
      database: ANALYTICS
      volatility: deterministic
    arguments:
      - name: first_name
        data_type: varchar
      - name: id
        data_type: number(38,0)
    returns:
      data_type: varchar
